import os
import json
from pathlib import Path

import pandas as pd
import streamlit as st

from utils import (
    build_output_json,
    load_marks_csv,
    merge_questions_with_marks,
    parse_pages_value,
    save_output_json,
    render_pdf_page,
    get_pdf_total_pages,
)


def process_script_data(pending_file_path: Path) -> dict:
    """Core logic to process a pending script JSON and return the verified payload."""
    with open(pending_file_path, "r") as f:
        data = json.load(f)

    # Calculate relative path from data/pending root to resolve matching files
    pending_root = Path("data/pending")
    try:
        rel_path = pending_file_path.relative_to(pending_root).parent
    except ValueError:
        rel_path = Path(".")

    doc_id = data.get("document_id", pending_file_path.stem)
    csv_id = doc_id.replace("ds_", "gt_")
    
    # Resolve CSV path using the mirrored relative structure
    csv_path = Path("data/marks") / rel_path / f"{csv_id}.csv"

    marks_map = {}
    if csv_path.exists():
        marks_map = load_marks_csv(str(csv_path))

    merged = merge_questions_with_marks(data.get("questions", []), marks_map)

    # Use fallback for total_pages if needed, respecting subfolder structure
    total_pages = data.get("total_pages", 0)
    if not total_pages:
        pdf_path = Path("data/scripts") / rel_path / f"{doc_id}.pdf"
        if pdf_path.exists():
            total_pages = get_pdf_total_pages(str(pdf_path))

    return build_output_json(
        document_id=doc_id,
        total_pages=total_pages,
        questions=merged,
    )


st.set_page_config(page_title="Ground Truth Verifier", layout="wide")
st.title("Ground Truth Verification Dashboard")
st.write("Review and verify candidate ground-truth JSONs generated by the batch processor.")

# --- Session State (Initialize Early) ---
if "editable_df" not in st.session_state:
    st.session_state.editable_df = pd.DataFrame(columns=["question_id", "pages", "obtained_marks"])
if "document_id" not in st.session_state:
    st.session_state.document_id = ""
if "total_pages" not in st.session_state:
    st.session_state.total_pages = 0
if "current_page" not in st.session_state:
    st.session_state.current_page = 1
if "last_selected" not in st.session_state:
    st.session_state.last_selected = ""
if "file_index" not in st.session_state:
    st.session_state.file_index = 0

# --- Sidebar: Verification Hub ---
st.sidebar.title("Verification Hub")

# Export Settings
export_path_str = st.sidebar.text_input("Export Directory", value="data/output/", help="Path where verified JSONs will be saved.")
export_root = Path(export_path_str)

# Global Safety Toggle
force_overwrite_all = st.sidebar.checkbox("Force Overwrite All", value=False, help="Allow bulk export to overwrite existing files in the output directory.")

st.sidebar.divider()

# Script Selection
pending_root = Path("data/pending")
# Use rglob for recursive discovery of pending files
pending_files = sorted(list(pending_root.rglob("*.json")))

if not pending_files:
    st.sidebar.info("No pending files found. Run `python src/batch_processor.py` first.")
    selected_file = None
else:
    # Use relative paths for display names to distinguish between nested files
    file_display_map = {str(f.relative_to(pending_root)): f for f in pending_files}
    file_names = list(file_display_map.keys())
    
    # Ensure file_index is within bounds
    st.session_state.file_index = min(st.session_state.file_index, len(file_names) - 1)

    selected_rel_path = st.sidebar.radio(
        "Select a script to verify", 
        file_names,
        index=st.session_state.file_index
    )
    
    # Update file_index based on radio selection
    st.session_state.file_index = file_names.index(selected_rel_path)
    selected_file = file_display_map[selected_rel_path]

    st.sidebar.divider()
    if st.sidebar.button("🚀 Export All Pending", use_container_width=True):
        progress_bar = st.sidebar.progress(0)
        total = len(pending_files)
        exported_count = 0
        skipped_count = 0
        
        for i, pf in enumerate(pending_files):
            try:
                # Mirror the nested folder structure in the output
                rel_path = pf.relative_to(pending_root).parent
                payload = process_script_data(pf)
                doc_id = payload["document_id"]
                
                target_dir = export_root / rel_path
                output_path = target_dir / f"{doc_id}.json"
                
                # Bulk Safety Check
                if output_path.exists() and not force_overwrite_all:
                    skipped_count += 1
                    continue
                
                target_dir.mkdir(parents=True, exist_ok=True)
                save_output_json(payload, str(output_path))
                os.remove(pf)
                exported_count += 1
            except Exception as e:
                st.sidebar.error(f"Error exporting {pf.name}: {e}")
            progress_bar.progress((i + 1) / total)
        
        if skipped_count > 0:
            st.sidebar.warning(f"Export complete. Sent {exported_count} files. Skipped {skipped_count} existing files (enable 'Force Overwrite' to replace them).")
        else:
            st.sidebar.success(f"Bulk export of {exported_count} files complete.")
        st.rerun()

# --- Load Selected File ---
if selected_file and str(selected_file) != st.session_state.last_selected:
    st.session_state.current_page = 1
    try:
        payload = process_script_data(selected_file)
        doc_id = payload["document_id"]
        total_pages = payload["total_pages"]
        merged = payload["questions"]

        # Resolve relative path for UI warning checks
        rel_path = selected_file.relative_to(pending_root).parent
        csv_id = doc_id.replace("ds_", "gt_")
        csv_path = Path("data/marks") / rel_path / f"{csv_id}.csv"
        
        if not csv_path.exists():
            st.warning(f"Marks CSV not found for {doc_id} at {csv_path}. Defaulting marks to 0.")

        editable_rows = []
        for row in merged:
            editable_rows.append(
                {
                    "question_id": row["question_id"],
                    "pages": ",".join(str(x) for x in row["pages"]),
                    "obtained_marks": int(row["obtained_marks"]),
                }
            )
        
        st.session_state.editable_df = pd.DataFrame(editable_rows)
        st.session_state.document_id = doc_id
        st.session_state.total_pages = total_pages
        st.session_state.last_selected = str(selected_file)
    except Exception as e:
        st.error(f"Error loading {selected_file.name}: {e}")

def _validate_questions_for_export(df: pd.DataFrame):
    errors = []
    for idx, row in df.iterrows():
        question_id = str(row.get("question_id", "")).strip() or f"row_{idx + 1}"
        raw_pages = row.get("pages", "")
        try:
            pages = parse_pages_value(raw_pages)
        except Exception:
            errors.append(f"{question_id} (invalid pages format)")
            continue
    return errors

# --- Verification UI ---
if not st.session_state.editable_df.empty:
    # Layout favoring the marks table for better visibility
    col_pdf, col_table = st.columns([1, 1.5])
    
    with col_pdf:
        with st.container():
            st.subheader(f"Script: {st.session_state.document_id}")
            
            # Resolve relative PDF path based on selected script
            rel_path = Path(st.session_state.last_selected).relative_to(pending_root).parent
            pdf_path = Path("data/scripts") / rel_path / f"{st.session_state.document_id}.pdf"
            
            if pdf_path.exists():
                # Render and Display Page
                try:
                    img_bytes = render_pdf_page(str(pdf_path), st.session_state.current_page)
                    # Fixed width of 700px for legibility and zoom-out support
                    st.image(img_bytes, width=700)
                except Exception as e:
                    st.error(f"Failed to render page {st.session_state.current_page}: {e}")                
                st.info(f"Viewing Physical Page {st.session_state.current_page}")
            else:
                st.warning(f"PDF not found at {pdf_path}")

    with col_table:
        # Script Navigation Row
        nav_col1, nav_col2, page_col = st.columns([1, 1, 1.5])
        with nav_col1:
            if st.button("⬅️ Previous", use_container_width=True, disabled=st.session_state.file_index == 0):
                st.session_state.file_index -= 1
                st.session_state.current_page = 1
                st.rerun()
        with nav_col2:
            if st.button("Next ➡️", use_container_width=True, disabled=st.session_state.file_index >= len(file_names) - 1):
                st.session_state.file_index += 1
                st.session_state.current_page = 1
                st.rerun()
        
        with page_col:
            jump_page = st.number_input(
                "Jump to Page",
                min_value=1,
                max_value=st.session_state.total_pages,
                value=st.session_state.current_page,
                key="jump_page_input"
            )
            if jump_page != st.session_state.current_page:
                st.session_state.current_page = jump_page
                st.rerun()

        st.subheader("Question Mapping")
        st.info(f"Total Pages in PDF: {st.session_state.total_pages}")
        st.write("Review and edit question page ranges.")
        
        edited_df = st.data_editor(
            st.session_state.editable_df,
            num_rows="dynamic",
            use_container_width=True,
            key="questions_editor",
        )
        st.session_state.editable_df = edited_df

        # Individual Overwrite Safety Check
        rel_path = Path(st.session_state.last_selected).relative_to(pending_root).parent
        target_output_path = export_root / rel_path / f"{st.session_state.document_id}.json"
        
        can_export = True
        if target_output_path.exists():
            st.warning(f"⚠️ `{st.session_state.document_id}.json` already exists in output.")
            confirm_overwrite = st.checkbox("Confirm Overwrite", value=False)
            can_export = confirm_overwrite

        if st.button("Export Verified Ground Truth", type="primary", disabled=not can_export):
            try:
                validation_errors = _validate_questions_for_export(st.session_state.editable_df)
                if validation_errors:
                    st.error("Validation failed. Please fix page values.")
                    st.write(", ".join(validation_errors))
                    st.stop()

                questions = []
                for _, row in st.session_state.editable_df.iterrows():
                    question_id = str(row["question_id"]).strip()
                    if not question_id: continue
                    pages = parse_pages_value(row["pages"])
                    obtained_marks = int(row["obtained_marks"])
                    questions.append({
                        "question_id": question_id,
                        "pages": pages,
                        "obtained_marks": obtained_marks,
                    })

                payload = build_output_json(
                    document_id=st.session_state.document_id,
                    total_pages=st.session_state.total_pages,
                    questions=questions,
                )
                
                # Mirror directory structure on final export
                target_output_path.parent.mkdir(parents=True, exist_ok=True)
                save_output_json(payload, str(target_output_path))

                # Cleanup pending file
                if selected_file and selected_file.exists():
                    os.remove(selected_file)
                    st.sidebar.success(f"Removed {selected_rel_path} from pending.")

                st.success(f"Verified JSON exported to: {output_path}")
                st.balloons()
                st.json(payload)
                
                # Reset state for next script
                st.session_state.editable_df = pd.DataFrame(columns=["question_id", "pages", "obtained_marks"])
                st.session_state.document_id = ""
                st.session_state.last_selected = ""
                st.rerun()
                
            except Exception as exc:
                st.error(f"Error during export: {exc}")
else:
    st.info("Select a file from the sidebar to begin verification.")
