import os
import json
from pathlib import Path

import pandas as pd
import streamlit as st

from utils import (
    build_output_json,
    load_marks_csv,
    merge_questions_with_marks,
    parse_pages_value,
    save_output_json,
    render_pdf_page,
)


st.set_page_config(page_title="Ground Truth Verifier", layout="wide")
st.title("Ground Truth Verification Dashboard")
st.write("Review and verify candidate ground-truth JSONs generated by the batch processor.")

# --- Session State (Initialize Early) ---
if "editable_df" not in st.session_state:
    st.session_state.editable_df = pd.DataFrame(columns=["question_id", "pages", "obtained_marks"])
if "document_id" not in st.session_state:
    st.session_state.document_id = ""
if "total_pages" not in st.session_state:
    st.session_state.total_pages = 0
if "current_page" not in st.session_state:
    st.session_state.current_page = 1
if "last_selected" not in st.session_state:
    st.session_state.last_selected = ""

# --- Sidebar: Pending Files ---
st.sidebar.title("Verification Hub")

# Export Settings
export_path = st.sidebar.text_input("Export Directory", value="data/output/", help="Path where verified JSONs will be saved.")

# Script Selection
pending_dir = Path("data/pending")
pending_files = sorted(list(pending_dir.glob("*.json")))

if not pending_files:
    st.sidebar.info("No pending files found.")
    selected_file = None
else:
    file_names = [f.name for f in pending_files]
    
    # Safe index for radio selection
    default_index = 0
    if st.session_state.get("last_selected"):
        last_name = Path(st.session_state.last_selected).name
        if last_name in file_names:
            default_index = file_names.index(last_name)

    selected_file_name = st.sidebar.radio(
        "Select a script to verify", 
        file_names,
        index=default_index
    )
    selected_file = pending_dir / selected_file_name

# --- Load Selected File ---
if selected_file and str(selected_file) != st.session_state.last_selected:
    st.session_state.current_page = 1
    try:
        with open(selected_file, "r") as f:
            data = json.load(f)
        
        doc_id = data.get("document_id", selected_file.stem)
        # Map back to CSV to get marks
        csv_id = doc_id.replace("ds_", "gt_")
        csv_path = Path("data/marks") / f"{csv_id}.csv"
        
        marks_map = {}
        if csv_path.exists():
            marks_map = load_marks_csv(str(csv_path))
        else:
            st.warning(f"Marks CSV not found for {doc_id} at {csv_path}. Defaulting marks to 0.")
            
        merged = merge_questions_with_marks(data.get("questions", []), marks_map)
        
        editable_rows = []
        for row in merged:
            editable_rows.append(
                {
                    "question_id": row["question_id"],
                    "pages": ",".join(str(x) for x in row["pages"]),
                    "obtained_marks": int(row["obtained_marks"]),
                }
            )
        
        st.session_state.editable_df = pd.DataFrame(editable_rows)
        st.session_state.document_id = doc_id
        st.session_state.total_pages = data.get("total_pages", 0)
        st.session_state.last_selected = str(selected_file)
    except Exception as e:
        st.error(f"Error loading {selected_file.name}: {e}")

def _validate_questions_for_export(df: pd.DataFrame):
    errors = []
    for idx, row in df.iterrows():
        question_id = str(row.get("question_id", "")).strip() or f"row_{idx + 1}"
        raw_pages = row.get("pages", "")
        try:
            pages = parse_pages_value(raw_pages)
        except Exception:
            errors.append(f"{question_id} (invalid pages format)")
            continue
    return errors

# --- Verification UI ---
if not st.session_state.editable_df.empty:
    col_pdf, col_table = st.columns([1, 1])
    
    with col_pdf:
        st.subheader(f"Script: {st.session_state.document_id}")
        pdf_path = Path("data/scripts") / f"{st.session_state.document_id}.pdf"
        
        if pdf_path.exists():
            # Navigation Bar
            nav_col1, nav_col2, nav_col3 = st.columns([1, 2, 1])
            with nav_col1:
                if st.button("Previous", disabled=st.session_state.current_page <= 1, use_container_width=True):
                    st.session_state.current_page -= 1
                    st.rerun()
            with nav_col2:
                st.markdown(f"<h3 style='text-align: center;'>Page {st.session_state.current_page} / {st.session_state.total_pages}</h3>", unsafe_allow_html=True)
            with nav_col3:
                if st.button("Next", disabled=st.session_state.current_page >= st.session_state.total_pages, use_container_width=True):
                    st.session_state.current_page += 1
                    st.rerun()

            # Render and Display Page
            img_bytes = render_pdf_page(str(pdf_path), st.session_state.current_page)
            st.image(img_bytes, use_container_width=True)
            
            st.info(f"Viewing Physical Page {st.session_state.current_page}")
        else:
            st.warning(f"PDF not found at {pdf_path}")

    with col_table:
        st.subheader("Question Mapping")
        st.info(f"Total Pages in PDF: {st.session_state.total_pages}")
        st.write("Review detected question pages. Double-click cells to edit.")
        
        edited_df = st.data_editor(
            st.session_state.editable_df,
            num_rows="dynamic",
            use_container_width=True,
            key="questions_editor",
        )
        st.session_state.editable_df = edited_df

        if st.button("Export Verified Ground Truth", type="primary"):
            try:
                validation_errors = _validate_questions_for_export(st.session_state.editable_df)
                if validation_errors:
                    st.error("Validation failed. Please fix page values for these questions:")
                    st.write(", ".join(validation_errors))
                    st.stop()

                questions = []
                for _, row in st.session_state.editable_df.iterrows():
                    question_id = str(row["question_id"]).strip()
                    if not question_id:
                        continue
                    pages = parse_pages_value(row["pages"])
                    obtained_marks = int(row["obtained_marks"])
                    questions.append(
                        {
                            "question_id": question_id,
                            "pages": pages,
                            "obtained_marks": obtained_marks,
                        }
                    )

                payload = build_output_json(
                    document_id=st.session_state.document_id,
                    total_pages=st.session_state.total_pages,
                    questions=questions,
                )
                
                output_dir = Path(export_path)
                output_dir.mkdir(parents=True, exist_ok=True)
                output_path = output_dir / f"{st.session_state.document_id}.json"
                save_output_json(payload, str(output_path))

                # Remove from pending after successful export
                if selected_file and selected_file.exists():
                    os.remove(selected_file)
                    st.sidebar.success(f"Removed {selected_file.name} from pending.")

                st.success(f"Verified JSON exported to: {output_path}")
                st.balloons()
                st.json(payload)
                
                # Reset state for next file
                st.session_state.editable_df = pd.DataFrame(columns=["question_id", "pages", "obtained_marks"])
                st.session_state.document_id = ""
                st.session_state.last_selected = ""
                st.rerun()
                
            except Exception as exc:
                st.error(f"Error during export: {exc}")
else:
    st.info("Select a file from the sidebar to begin verification.")
